modLoader="javafml"
loaderVersion="[35,)"
license="All rights reserved"
issueTrackerURL="https://github.com/Meldexun/EntityCulling/issues"
[[mods]]
modId="entity_culling"
version="2.1.6"
displayName="Entity Culling"
authors="Meldexun"
description='''
'''
